//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Full_Fare.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class FullFare
    {
        public int OBJECTID_1 { get; set; }
        public string APN { get; set; }
        public string APNLINK { get; set; }
        public string APNLINK2 { get; set; }
        public string RELATE_KEY { get; set; }
        public Nullable<double> AREA { get; set; }
        public Nullable<double> PERIMETER { get; set; }
        public Nullable<double> PARCELS_ { get; set; }
        public Nullable<double> PARCELS_ID { get; set; }
        public string ADDRESSPRP { get; set; }
        public Nullable<double> Situs_House_No_House_Alpha { get; set; }
        public string Situs_Direction_Street_Suffix { get; set; }
        public string Situs_City_State_ZIP_ZIP_4_DWL { get; set; }
        public string Situs_ZIP_ZIP_4 { get; set; }
        public string Situs_Carrier_Route { get; set; }
        public string Owner_Name__First_Name_First_ { get; set; }
        public string Owner_First_Name { get; set; }
        public string Owner_Middle_Name { get; set; }
        public string Owner_Last_Name { get; set; }
        public string Owner_Spouse_First_Middle { get; set; }
        public string Owner_2 { get; set; }
        public string Mail_Care_Of_Name { get; set; }
        public string Mail_Address { get; set; }
        public string Mail_City_State_ZIP_ZIP_4_DWL { get; set; }
        public string Mail_State_DWL { get; set; }
        public string Mail_ZIP_ZIP_4 { get; set; }
        public string Mail_Carrier_Route { get; set; }
        public string Phone_Number { get; set; }
        public string Land_Use { get; set; }
        public string Zoning { get; set; }
        public Nullable<double> Stories_No { get; set; }
        public string No_Residential_Units { get; set; }
        public Nullable<double> Gross_Area { get; set; }
        public Nullable<double> Bldg_Living_Area { get; set; }
        public string Adj_Area__Total_ { get; set; }
        public string Basement_Area { get; set; }
        public Nullable<double> Total_Rooms { get; set; }
        public Nullable<double> Bedrooms { get; set; }
        public Nullable<double> Baths__Total_ { get; set; }
        public Nullable<double> Baths__Full_ { get; set; }
        public string Baths__Half_ { get; set; }
        public string Fixtures_Number { get; set; }
        public string Pool { get; set; }
        public Nullable<double> Fireplace_Number { get; set; }
        public string Parking_Type { get; set; }
        public string Parking_Size { get; set; }
        public string Parking_Type2_Code { get; set; }
        public string Garage_2_Area { get; set; }
        public Nullable<double> Sale_Price { get; set; }
        public Nullable<double> Price_per_Square_Foot { get; set; }
        public string Sale_Price_Type1_DWL { get; set; }
        public string Sale_Type_2 { get; set; }
        public Nullable<System.DateTime> Recording_Date { get; set; }
        public Nullable<System.DateTime> Sale_Date { get; set; }
        public string Document_Number { get; set; }
        public Nullable<double> st_TD_Amount { get; set; }
        public string st_TD_Loan_Type { get; set; }
        public Nullable<double> st_TD_Term_No { get; set; }
        public Nullable<double> st_TD_Int_Rate { get; set; }
        public string st_TD_Int_Rate_Type { get; set; }
        public string Deed_Type { get; set; }
        public string Lender { get; set; }
        public Nullable<double> Prior_Sale_Price { get; set; }
        public string Prior_Sale_Type_Code1 { get; set; }
        public Nullable<System.DateTime> Prior_Sale_Date { get; set; }
        public string Seller { get; set; }
        public string Construction_Type { get; set; }
        public string Foundation { get; set; }
        public string Exterior_Wall { get; set; }
        public string Roof_Material_Type { get; set; }
        public string Roof_Type { get; set; }
        public string Interior_Wall { get; set; }
        public string Air_Conditioning { get; set; }
        public string Heat_Fuel { get; set; }
        public string Heat_Type { get; set; }
        public string Frame { get; set; }
        public string Floor_Type { get; set; }
        public Nullable<double> Assessment_Year { get; set; }
        public Nullable<double> Land_Value { get; set; }
        public Nullable<double> Improvement_Value { get; set; }
        public Nullable<double> Total_Value { get; set; }
        public Nullable<double> Total_Value__Taxable_ { get; set; }
        public Nullable<double> Property_Tax { get; set; }
        public Nullable<double> Tax_Area { get; set; }
        public Nullable<double> Lot_Acreage { get; set; }
        public Nullable<double> Lot_Area { get; set; }
        public Nullable<double> County_Land_Use { get; set; }
        public string State_Use { get; set; }
        public string Improvement_Type { get; set; }
        public string Site_Influence { get; set; }
        public string Site_Waterfront { get; set; }
        public string Alt_Old_APN { get; set; }
        public string APN_Card_First { get; set; }
        public string APN_Card_Last { get; set; }
        public string Map_Ref1 { get; set; }
        public string Map_Ref2 { get; set; }
        public string Municipality { get; set; }
        public Nullable<double> Year_Built { get; set; }
        public string Year_Built__Effective_ { get; set; }
        public string Township_Range_Section { get; set; }
        public Nullable<double> Census_Tract { get; set; }
        public string Subdivision { get; set; }
        public string Legal_Block { get; set; }
        public string Legal_Lot { get; set; }
        public string Legal_Plat_BkPg { get; set; }
        public string Legal_Description { get; set; }
    }
}
